# Generated by Django 6.0.8 on 2026-08-31 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="COMPANY_ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="NAME", max_length=255)),
                (
                    "cnpj",
                    models.CharField(db_column="CNPJ", max_length=18, unique=True),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True, db_column="PROJECT_ID", max_length=200, null=True
                    ),
                ),
                (
                    "deal_id",
                    models.CharField(
                        blank=True, db_column="DEAL_ID", max_length=200, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_column="STATUS",
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UPDATED_AT"),
                ),
            ],
            options={
                "verbose_name": "Financials Company",
                "verbose_name_plural": "Financials Companies",
                "db_table": "FINANCIALS_COMPANY",
                "ordering": ["name"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AccountChart",
            fields=[
                (
                    "account_code",
                    models.CharField(
                        db_column="ACCOUNT_CODE",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(db_column="ACCOUNT_NAME", max_length=255),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                            ("RESULT", "Result"),
                        ],
                        db_column="ACCOUNT_TYPE",
                        max_length=20,
                    ),
                ),
                (
                    "statement",
                    models.CharField(
                        choices=[
                            ("BALANCE_SHEET", "Balance Sheet"),
                            ("INCOME_STATEMENT", "Income Statement"),
                        ],
                        db_column="STATEMENT",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(db_column="LEVEL", default=0),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_column="DISPLAY_ORDER", default=0),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("CUSTOM", "Custom")],
                        db_column="ORIGIN",
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="PARENT_CODE",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="financials.accountchart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Chart Entry",
                "verbose_name_plural": "Account Chart",
                "db_table": "FINANCIALS_ACCOUNT_CHART",
                "ordering": ["statement", "display_order", "account_code"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="STATEMENT_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("BALANCE_SHEET", "Balance Sheet"),
                            ("INCOME_STATEMENT", "Income Statement"),
                        ],
                        db_column="STATEMENT_TYPE",
                        max_length=20,
                    ),
                ),
                ("period_end_date", models.DateField(db_column="PERIOD_END_DATE")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        db_column="PERIOD_TYPE",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(db_column="CURRENCY", default="BRL", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINAL", "Final")],
                        db_column="STATUS",
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "extracted_by",
                    models.CharField(
                        blank=True, db_column="EXTRACTED_BY", max_length=100, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="COMPANY_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="financials.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Statement",
                "verbose_name_plural": "Financial Statements",
                "db_table": "FINANCIALS_STATEMENT",
                "ordering": ["-period_end_date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FinancialStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="LINE_ID", primary_key=True, serialize=False
                    ),
                ),
                ("raw_label", models.CharField(db_column="RAW_LABEL", max_length=500)),
                (
                    "value",
                    models.DecimalField(
                        db_column="VALUE", decimal_places=2, max_digits=20
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="NOTES", null=True)),
                (
                    "account",
                    models.ForeignKey(
                        db_column="ACCOUNT_CODE",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statement_lines",
                        to="financials.accountchart",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        db_column="STATEMENT_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financials.financialstatement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Statement Line",
                "verbose_name_plural": "Financial Statement Lines",
                "db_table": "FINANCIALS_STATEMENT_LINE",
                "ordering": ["id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="DOCUMENT_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "stage_path",
                    models.CharField(
                        db_column="STAGE_PATH", max_length=1000, unique=True
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(db_column="ORIGINAL_FILENAME", max_length=500),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("XLSX", "XLSX")],
                        db_column="FILE_TYPE",
                        max_length=10,
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, db_column="UPLOAD_DATE"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARSING", "Parsing"),
                            ("PARSED", "Parsed"),
                            ("FAILED", "Failed"),
                        ],
                        db_column="PROCESSING_STATUS",
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "parsed_text",
                    models.TextField(blank=True, db_column="PARSED_TEXT", null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="COMPANY_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_documents",
                        to="financials.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financials Source Document",
                "verbose_name_plural": "Financials Source Documents",
                "db_table": "FINANCIALS_SOURCE_DOCUMENT",
                "ordering": ["-upload_date"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="financialstatement",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                db_column="SOURCE_DOCUMENT_ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statements",
                to="financials.sourcedocument",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialstatement",
            unique_together={("company", "statement_type", "period_end_date")},
        ),
    ]
